"""Prompts package for AI Contributor Summaries."""

from .prompt_templates import (
    ISSUES_SYSTEM_PROMPT,
    COMMITS_SYSTEM_PROMPT,
    REPO_WORK_SYSTEM_PROMPT,
    CONTRIBUTOR_SYSTEM_PROMPT,
    SKILLS_EXTRACTION_PROMPT,
    TECHNOLOGY_DETECTION_PROMPT,
    EXPERTISE_LEVEL_PROMPT
)

__all__ = [
    "ISSUES_SYSTEM_PROMPT",
    "COMMITS_SYSTEM_PROMPT", 
    "REPO_WORK_SYSTEM_PROMPT",
    "CONTRIBUTOR_SYSTEM_PROMPT",
    "SKILLS_EXTRACTION_PROMPT",
    "TECHNOLOGY_DETECTION_PROMPT",
    "EXPERTISE_LEVEL_PROMPT"
]